### ISSUE TITLE
Could not pass EntityDamageByEntityEvent on v4.0.0-RC1

### ISSUE THREAD

**Issue by HyperKids** [MediusEcho/ParticleHatsWiki#7]
Occurs when punching a Citizen NPC. Completely destroys KitPvP plugins that I am using as well...

[22:36:02 ERROR]: Could not pass event EntityDamageByEntityEvent to ParticleHats v4.0.0-RC1
java.lang.NullPointerException: null
        at com.mediusecho.particlehats.player.PlayerState.<init>(PlayerState.java:60) ~[?:?]
        at com.mediusecho.particlehats.ParticleHats.getPlayerState(ParticleHats.java:308) ~[?:?]
        at com.mediusecho.particlehats.listeners.EntityListener.handleCombat(EntityListener.java:124) ~[?:?]
        at com.mediusecho.particlehats.listeners.EntityListener.onEntityDamage(EntityListener.java:69) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1431.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-86]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:223) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:968) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:867) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1000) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity0(EntityLiving.java:1680) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity0(EntityHuman.java:847) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1095) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity(EntityHuman.java:770) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.EntityPlayer.damageEntity(EntityPlayer.java:743) ~[patched_1.14.2.jar:git-Paper-86]
        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:142) ~[?:?]
        at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1031) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1668) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2063) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:975) ~[patched_1.14.2.jar:git-Paper-86]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-86]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by momoservertw** [comment]
I have this error too.
Please~~

**Comment by MediusEcho** [comment]
Uploaded a new version with a fix.
 [https://github.com/MediusEcho/ParticleHatsWiki/releases/tag/4.0.0-RC2](https://github.com/MediusEcho/ParticleHatsWiki/releases/tag/4.0.0-RC2)
